### PR TITLE
add private method to convert utc to local

### PR DESCRIPTION
**Pull request by Brewer-Slack**
Let me know if this misses anything. For some reason I'm unable to upload to my localhost so I can't verify that this works.

### CODE REVIEW

**Review by aniehuser — CHANGES_REQUESTED** [review]
This merge breaks the build, here's where its occuring:
```
   File "/home/travis/build/aniehuser/senior-design-group10/yw_website/yw_website/apps/website/serializers.py", line 213, in create
    last_modified=self._utc_to_local(datetime.datetime.now(tz=timezone.utc)),
TypeError: _utc_to_local() takes 1 positional argument but 2 were given
```

you need to fix this before we merge

**Comment by Brewer-Slack** [comment]
I can't figure out why replace() is failing. I will look more into this tomorrow. It seems like people online have also had this issue.

**Comment by Brewer-Slack** [comment]
The issue is that django is set to be in the UTC timezone, which prevents me from detecting the current timezone. I'm looking into this.

**Comment by Brewer-Slack** [comment]
To clarify here, the tests are passing on my machine and are giving the proper timestamps. However, there are still tests that are failing because of this error `django.db.utils.OperationalError: no such table: main.website_data__old`

**Comment by Brewer-Slack** [comment]
Should be all working.

**Review by aniehuser — APPROVED** [review]
awesome, this looks great. good sleuthing

**Review by clundin55 — APPROVED** [review]

**Pull request merged**
