### PR TITLE
Added er diagram website file and an er diagram png so we can track i…

### PR DESCRIPTION
**Pull request by clundin55**
…t with our project.

### CODE REVIEW

**Comment by smbowers** [comment]
1. I think there should be a User entity type (with UserID, LoginName, SHPassword, etc.). Then there would be a Creator relationship between a User and a Workflow. (SHPassword means salted and hashed password -- could call this EncPassword for encrypted password, etc. -- I believe Django actually takes care of the salt and hashing for you) 
2. The double lines around relationship types are not necessary (only used for weak entities and identifying relationships). I think you are using these (at least in most places) to mean a foreign key. Instead, just give it the relationships a name (e.g., WorkflowVersion, VersionRun, ..., or VersionOf, RunOf). Foreign keys are implied by the relationship. 
3.  Try to specify both min and max constraints. So, e.g., how many tags must a Workflow have (probably zero). 
4. I think for the Version, the Model is a from yw, so maybe call it ywModelCheckSum for consistency. 
5. You need cardinality constraints on the RunFile relationship. I'm not sure I understand what the (runId, fileCheckSum) composite key is about on the RunFile relationship ... this looks suspicious to me.
6. It isn't clear to me what "Input Data (O)" means in File.

**Comment by clundin55** [comment]
The (O) means that the attribute is optional. I will apply the other suggestions.

**Review by aniehuser — COMMENTED** [review]
Probably ready to go now yes?

it looks good to me

**Comment by clundin55** [comment]
@aniehuser yes

**Comment by clundin55** [comment]
@aniehuser will you approve this

**Review by aniehuser — APPROVED** [review]
LGTM

**Pull request merged**
