### PR TITLE
Added yw jar to server repo

### PR DESCRIPTION
**Pull request by clundin55**

### CODE REVIEW

**Review by aniehuser — CHANGES_REQUESTED** [review]
Could you specify the commit you used to build this? just like `yesworkflow-<commit-id>.jar` just so we know what version of cli we're working with

**Comment by clundin55** [comment]
> Could you specify the commit you used to build this? just like `yesworkflow-<commit-id>.jar` just so we know what version of cli we're working with

@aniehuser done

**Comment by aniehuser** [comment]
you misspelled yesworkflow :/
> yyesworkflow-39af8d267.jar

**Comment by clundin55** [comment]
@aniehuser done

**Review by aniehuser — APPROVED** [review]

**Pull request merged**
