### PR TITLE
added a route to handle post request from yw

### PR DESCRIPTION
**Pull request by aniehuser**

### CODE REVIEW

**Comment by aniehuser** [comment]
still need to add tests, just wanted to get something out for demo

**Review by clundin55 — DISMISSED** [review]
LGTM. Please merge the PR for removing all the binaries, and then remove all the binaries from this PR so we don't reintroduce them to master.

**Comment by aniehuser** [comment]
@clundin55 @mbrown20 @bthuntington @Brewer-Slack migrations removed from commit

**Comment by clundin55** [comment]
@aniehuser is this ready to be merged?

**Comment by aniehuser** [comment]
@clundin55 for the prototype, yes. For our standards probably not. It works, and allows for a raw string in dot file format to be uploaded from yw to our database.

**Comment by clundin55** [comment]
@aniehuser okay cool lets merge it then. I will start work on integrating the python graphviz module

**Review by Brewer-Slack — APPROVED** [review]
LGTM

**Comment by aniehuser** [comment]
Should check for merge conflicts before merging since we just merged the `prototype` branch

**Comment by clundin55** [comment]
@aniehuser is this merged?

**Pull request closed without merging**
