### PR TITLE
Refactor/urls.py

### PR DESCRIPTION
**Pull request by clundin55**
Added some comments and basic organization to urls.py. Subjective if its better but its a start.
Forgot to remove other commits again.

### CODE REVIEW

**Comment by clundin55** [comment]
@aniehuser  review this one last and the only changes that should be in this branch are to urls.py

**Review by aniehuser — CHANGES_REQUESTED** [review]
merge conflicts with your test PR

**Comment by clundin55** [comment]
@aniehuser i'll fix the conflicts when the other PR goes in.

**Comment by clundin55** [comment]
@aniehuser done

**Pull request closed without merging**
